CREATE TABLE IF NOT EXISTS reeval (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  datetime DATETIME NOT NULL,
  atend INT NOT NULL,
  age INT,
  sex VARCHAR(1) NOT NULL,
  medic VARCHAR(128) NOT NULL,
  score INT NOT NULL,
  problem1 BOOLEAN NOT NULL COMMENT "1ª anamnese pouco útil",
  problem2 BOOLEAN NOT NULL COMMENT "1ª anamnese incompatível com quadro",
  problem3 BOOLEAN NOT NULL COMMENT "Ausência de AP",
  problem4 BOOLEAN NOT NULL COMMENT "Ausência de MU",
  problem5 BOOLEAN NOT NULL COMMENT "Ausência de Alergias",
  problem6 BOOLEAN NOT NULL COMMENT "Ausência de EF",
  problem7 BOOLEAN NOT NULL COMMENT "EF incompatível com quadro",
  problem8 BOOLEAN NOT NULL COMMENT "Ausência de HD",
  problem9 BOOLEAN NOT NULL COMMENT "CD incompatível com quadro",
  problem10 BOOLEAN NOT NULL COMMENT "Exames desnecessários",
  problem11 BOOLEAN NOT NULL COMMENT "Exames errados (Labs/ECG)",
  problem12 BOOLEAN NOT NULL COMMENT "Exames errados (Imagens)",
  problem13 BOOLEAN NOT NULL COMMENT "Exames insuficientes",
  problem14 BOOLEAN NOT NULL COMMENT "Necessidade de re-reaval",
  problem15 BOOLEAN NOT NULL COMMENT "Outros",
  outros_problem TEXT
);