AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Gemspec/DevelopmentDependencies:
  Enabled: false
Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*.rb'