AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
plugins:
  - rubocop-rake
  - rubocop-rspec

Gemspec/DevelopmentDependencies:
  Enabled: false
Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*.rb'